"""jit layer

Revision ID: 13af3192976d
Revises: cf6afd3a25f3
Create Date: 2026-07-26 23:27:18.564073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '13af3192976d'
down_revision: Union[str, None] = 'cf6afd3a25f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
