"""per-market pools

Revision ID: 204d8803ecd3
Revises: 5df285b64390
Create Date: 2026-07-27 00:49:59.209703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '204d8803ecd3'
down_revision: Union[str, None] = '5df285b64390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
