"""market and order geo coordinates

Revision ID: 323b353fcf08
Revises: 3c066f9aba8b
Create Date: 2026-07-23 00:39:12.850624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '323b353fcf08'
down_revision: Union[str, None] = '3c066f9aba8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_agents_is_available'), 'agents', ['is_available'], unique=False)
    op.add_column('markets', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('markets', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('dropoff_latitude', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('dropoff_longitude', sa.Float(), nullable=True))
    op.alter_column('transactions', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('orders', 'dropoff_longitude')
    op.drop_column('orders', 'dropoff_latitude')
    op.drop_column('markets', 'longitude')
    op.drop_column('markets', 'latitude')
    op.drop_index(op.f('ix_agents_is_available'), table_name='agents')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
