"""prepay + flows

Revision ID: 3770cb348885
Revises: c5851ff60442
Create Date: 2026-07-29 02:03:15.671557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3770cb348885'
down_revision: Union[str, None] = 'c5851ff60442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
