"""money model

Revision ID: 3c066f9aba8b
Revises: 2a1f2d7acb6b
Create Date: 2026-07-22 18:37:40.463096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '3c066f9aba8b'
down_revision: Union[str, None] = '2a1f2d7acb6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=True)
    op.create_table('wallet_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    # ledgerdirection enum type already exists (created by float_ledger in an
    # earlier migration) — create_type=False so this doesn't try to redefine it.
    sa.Column(
        'direction',
        postgresql.ENUM('DEBIT', 'CREDIT', name='ledgerdirection', create_type=False),
        nullable=False,
    ),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_ledger_wallet_id'), 'wallet_ledger', ['wallet_id'], unique=False)
    op.add_column('orders', sa.Column('shopping_started_at', sa.DateTime(timezone=True), nullable=True))
    # NOT NULL with no default would fail on existing rows — backfill via a
    # temporary server_default, then drop it so it matches the model (which
    # only has a Python-side default, same as the other money columns).
    op.add_column(
        'orders',
        sa.Column(
            'estimated_value', sa.Numeric(precision=12, scale=2),
            nullable=False, server_default='0',
        ),
    )
    op.add_column(
        'orders',
        sa.Column(
            'deposit_amount', sa.Numeric(precision=12, scale=2),
            nullable=False, server_default='0',
        ),
    )
    op.alter_column('orders', 'estimated_value', server_default=None)
    op.alter_column('orders', 'deposit_amount', server_default=None)
    op.add_column('orders', sa.Column('deposit_paid_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('delivery_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'deposit_paid_at')
    op.drop_column('orders', 'deposit_amount')
    op.drop_column('orders', 'estimated_value')
    op.drop_column('orders', 'shopping_started_at')
    op.drop_index(op.f('ix_wallet_ledger_wallet_id'), table_name='wallet_ledger')
    op.drop_table('wallet_ledger')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_table('wallets')
    # ### end Alembic commands ###
