"""platform features

Revision ID: 4b6d4d8a8551
Revises: ce4119d76114
Create Date: 2026-07-23 01:51:58.261844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4b6d4d8a8551'
down_revision: Union[str, None] = 'ce4119d76114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
