"""per-market pools

Revision ID: 5df285b64390
Revises: 13af3192976d
Create Date: 2026-07-27 00:22:09.451988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5df285b64390'
down_revision: Union[str, None] = '13af3192976d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pool_locks',
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('market_id')
    )
    op.add_column('float_ledger', sa.Column('market_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_float_ledger_market_id'), 'float_ledger', ['market_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_float_ledger_market_id'), table_name='float_ledger')
    op.drop_column('float_ledger', 'market_id')
    op.drop_table('pool_locks')
    # ### end Alembic commands ###
