"""add location searches

Revision ID: 968b594f5176
Revises: f3a4b5c6d7e8
Create Date: 2026-09-17 19:20:04.165601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '968b594f5176'
down_revision: Union[str, None] = 'f3a4b5c6d7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_searches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_searches_label'), 'location_searches', ['label'], unique=False)
    op.create_index(op.f('ix_location_searches_user_id'), 'location_searches', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_searches_user_id'), table_name='location_searches')
    op.drop_index(op.f('ix_location_searches_label'), table_name='location_searches')
    op.drop_table('location_searches')
    # ### end Alembic commands ###
