"""must prepay flag

Revision ID: c5851ff60442
Revises: 204d8803ecd3
Create Date: 2026-07-29 01:56:58.440802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c5851ff60442'
down_revision: Union[str, None] = '204d8803ecd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # order_items/users already have rows, so the new NOT NULL columns need a
    # server_default to backfill them, then we drop the default so the schema
    # matches the model exactly (which only declares a Python-side default).
    op.add_column('order_items', sa.Column('listed_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('order_items', sa.Column('availability', sa.String(length=20), nullable=False, server_default='pending'))
    op.alter_column('order_items', 'availability', server_default=None)
    op.add_column('orders', sa.Column('packing_photos', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('must_prepay', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('users', 'must_prepay', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_prepay')
    op.drop_column('orders', 'packing_photos')
    op.drop_column('order_items', 'availability')
    op.drop_column('order_items', 'listed_price')
    # ### end Alembic commands ###
