"""agent applications

Revision ID: ce4119d76114
Revises: 323b353fcf08
Create Date: 2026-07-23 00:50:49.838015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ce4119d76114'
down_revision: Union[str, None] = '323b353fcf08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_applications_status'), 'agent_applications', ['status'], unique=False)
    op.create_index(op.f('ix_agent_applications_user_id'), 'agent_applications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_applications_user_id'), table_name='agent_applications')
    op.drop_index(op.f('ix_agent_applications_status'), table_name='agent_applications')
    op.drop_table('agent_applications')
    # ### end Alembic commands ###
