"""jit layer

Revision ID: cf6afd3a25f3
Revises: c229f2c72745
Create Date: 2026-07-26 20:22:22.458761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'cf6afd3a25f3'
down_revision: Union[str, None] = 'c229f2c72745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('stall_description', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sellers_market_id'), 'sellers', ['market_id'], unique=False)
    op.create_table('vendor_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('bank_code', sa.String(length=10), nullable=False),
    sa.Column('account_name', sa.String(length=120), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('is_third_party', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_accounts_account_number'), 'vendor_accounts', ['account_number'], unique=False)
    op.create_table('spending_authorizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('cap', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spending_authorizations_order_id'), 'spending_authorizations', ['order_id'], unique=True)
    op.create_table('vendor_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=True),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('bank_code', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('emtl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', name='transactionstatus', create_type=False), nullable=False),
    sa.Column('photo_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_transfers_order_id'), 'vendor_transfers', ['order_id'], unique=False)
    op.create_index(op.f('ix_vendor_transfers_reference'), 'vendor_transfers', ['reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_transfers_reference'), table_name='vendor_transfers')
    op.drop_index(op.f('ix_vendor_transfers_order_id'), table_name='vendor_transfers')
    op.drop_table('vendor_transfers')
    op.drop_index(op.f('ix_spending_authorizations_order_id'), table_name='spending_authorizations')
    op.drop_table('spending_authorizations')
    op.drop_index(op.f('ix_vendor_accounts_account_number'), table_name='vendor_accounts')
    op.drop_table('vendor_accounts')
    op.drop_index(op.f('ix_sellers_market_id'), table_name='sellers')
    op.drop_table('sellers')
    # ### end Alembic commands ###
