"""otp attempts counter

Revision ID: d195881af7a5
Revises: 3770cb348885
Create Date: 2026-07-29 14:14:27.978832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd195881af7a5'
down_revision: Union[str, None] = '3770cb348885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # otp_codes already has rows, so the new NOT NULL column needs a
    # server_default to backfill them, then we drop the default so the schema
    # matches the model exactly (which only declares a Python-side default).
    op.add_column('otp_codes', sa.Column('attempts', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('otp_codes', 'attempts', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_codes', 'attempts')
    # ### end Alembic commands ###
